dist: trusty
language: python
python:
  - '3.6'

# Install tox and codecov
install:
  - pip install tox-travis
  - pip install codecov

# Use tox to run tests in the matrix of environments
script:
- tox -r

# Push the results back to codecov
after_success:
  - coverage xml && codecov -f coverage.xml --commit=$TRAVIS_COMMIT

# Deploy updates on master to pypi, which will only succeed if there's been a version bump
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  edge: true
  user: __token__
  password:
    secure: DL6FAjStviZMGQl4YkLy0BqCN+ufsVA/Tm1fu/riSmdxMJMZCIcOmXqit/a0lr8bsX2regHfXGR1F+pQhlHTdJKU6awZKIjr7+i1xknizw+EmoNRBKLGMr7UaoiNfX4wKqP4eO2uoeyn1MQ0mlV9ojh9zxr6pUdOZ64SWw4eL3cKsF2g7nzhzGOAIk3tKpand0Re6axAofATG6DsthT3FBWWsXJcPbgMxAsfWj1z8yyOxGZiSWlWgnXjGfq6MZkY9YyIev+uf/HkzwaHw/ih3XeAhKP9HOImmihxK4GvtFbMJzctvUSxxDyTl3DGokOlKc5NhKMc+ERIgsJdp2Ikc2ngAMXyPOEfAG/CcjmbsZsmb/u5KCUjt77ZdO6D1gg3gn3rE8YqRrsKXJSe7tAWsY30y3N3n7F0nopayn018L1RmGSTbgrxVcm0r87g9a6hKAY3hqN8JEibFChukWgX9llAED8m45zQxTqDKY52+dnN9BLTLsjpO5nhUnvvT+InVHxxN6/l6GRD6eqtlXXkj2CU9z09GFvWoeUjPjkjnfFrSnbOuPhe+gxtB0YbdL+n7uOho6icvUO7u4pfiKuvkA9RRPPkkEh+e3ZVnw6fPU43lZXpiyjOvwQQNC7459R4sgb4hGmjtTshoDVSixpyyVpNk7PKexANxCIhEmIMKOY=
  on:
    branch: master
